stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - mimir
  only:
    - main
  script:
    - cd /opt/prettydiagrams
    - sudo -u ubuntu git pull origin main
    - sudo -u ubuntu .venv/bin/pip install -r requirements.txt --quiet
    - echo "PrettyDiagrams deployed"
